[package]
name = "gitea-sdk"
version = "0.6.3"
edition = "2021"
license = "MIT"
description = "An unofficial Gitea API client"
repository = "https://github.com/benpueschel/teatime"
readme = "README.md"
authors = ["Ben Püschel"]
keywords = ["git", "gitea", "api", "client"]
categories = ["api-bindings"]

[lib]

[dependencies]
base64 = "0.23.1"
build-it = "0.1.5"
reqwest = { version = "0.13.4", default-features = false, features = ["charset", "http2", "json", "native-tls", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
testcontainers = { version = "0.27.3", features = ["http_wait"] }
tokio = { version = "1.53.1", features = ["macros"] }
